name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy-to-ec2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USER}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            # docker pull image
            docker pull james66689/wits_calendar_backend:latest
            docker pull james66689/wits_calendar_frontend:latest

            cd /home/ubuntu
            docker-compose stop
            docker-compose up -d
